#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklep
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Sklep")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCzesci(Czesci instance);
    partial void UpdateCzesci(Czesci instance);
    partial void DeleteCzesci(Czesci instance);
    partial void InsertZakupy(Zakupy instance);
    partial void UpdateZakupy(Zakupy instance);
    partial void DeleteZakupy(Zakupy instance);
    partial void InsertKlient(Klient instance);
    partial void UpdateKlient(Klient instance);
    partial void DeleteKlient(Klient instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Sklep.Properties.Settings.Default.SklepConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Czesci> Czesci
		{
			get
			{
				return this.GetTable<Czesci>();
			}
		}
		
		public System.Data.Linq.Table<Zakupy> Zakupy
		{
			get
			{
				return this.GetTable<Zakupy>();
			}
		}
		
		public System.Data.Linq.Table<Klient> Klient
		{
			get
			{
				return this.GetTable<Klient>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Czesci")]
	public partial class Czesci : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Czesci;
		
		private string _Marka;
		
		private string _Model;
		
		private string _Rodzaj_Paliwa;
		
		private string _Silnik;
		
		private string _Typ_Czesci;
		
		private string _Nazwa_Czesci;
		
		private string _Numer_Katalogowy;
		
		private System.Nullable<int> _Stan_Magazyn;
		
		private EntitySet<Zakupy> _Zakupy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_CzesciChanging(int value);
    partial void OnId_CzesciChanged();
    partial void OnMarkaChanging(string value);
    partial void OnMarkaChanged();
    partial void OnModelChanging(string value);
    partial void OnModelChanged();
    partial void OnRodzaj_PaliwaChanging(string value);
    partial void OnRodzaj_PaliwaChanged();
    partial void OnSilnikChanging(string value);
    partial void OnSilnikChanged();
    partial void OnTyp_CzesciChanging(string value);
    partial void OnTyp_CzesciChanged();
    partial void OnNazwa_CzesciChanging(string value);
    partial void OnNazwa_CzesciChanged();
    partial void OnNumer_KatalogowyChanging(string value);
    partial void OnNumer_KatalogowyChanged();
    partial void OnStan_MagazynChanging(System.Nullable<int> value);
    partial void OnStan_MagazynChanged();
    #endregion
		
		public Czesci()
		{
			this._Zakupy = new EntitySet<Zakupy>(new Action<Zakupy>(this.attach_Zakupy), new Action<Zakupy>(this.detach_Zakupy));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Czesci", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id_Czesci
		{
			get
			{
				return this._Id_Czesci;
			}
			set
			{
				if ((this._Id_Czesci != value))
				{
					this.OnId_CzesciChanging(value);
					this.SendPropertyChanging();
					this._Id_Czesci = value;
					this.SendPropertyChanged("Id_Czesci");
					this.OnId_CzesciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marka", DbType="NVarChar(100)")]
		public string Marka
		{
			get
			{
				return this._Marka;
			}
			set
			{
				if ((this._Marka != value))
				{
					this.OnMarkaChanging(value);
					this.SendPropertyChanging();
					this._Marka = value;
					this.SendPropertyChanged("Marka");
					this.OnMarkaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Model", DbType="NVarChar(100)")]
		public string Model
		{
			get
			{
				return this._Model;
			}
			set
			{
				if ((this._Model != value))
				{
					this.OnModelChanging(value);
					this.SendPropertyChanging();
					this._Model = value;
					this.SendPropertyChanged("Model");
					this.OnModelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rodzaj_Paliwa", DbType="NVarChar(100)")]
		public string Rodzaj_Paliwa
		{
			get
			{
				return this._Rodzaj_Paliwa;
			}
			set
			{
				if ((this._Rodzaj_Paliwa != value))
				{
					this.OnRodzaj_PaliwaChanging(value);
					this.SendPropertyChanging();
					this._Rodzaj_Paliwa = value;
					this.SendPropertyChanged("Rodzaj_Paliwa");
					this.OnRodzaj_PaliwaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Silnik", DbType="NVarChar(100)")]
		public string Silnik
		{
			get
			{
				return this._Silnik;
			}
			set
			{
				if ((this._Silnik != value))
				{
					this.OnSilnikChanging(value);
					this.SendPropertyChanging();
					this._Silnik = value;
					this.SendPropertyChanged("Silnik");
					this.OnSilnikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Typ_Czesci", DbType="NVarChar(100)")]
		public string Typ_Czesci
		{
			get
			{
				return this._Typ_Czesci;
			}
			set
			{
				if ((this._Typ_Czesci != value))
				{
					this.OnTyp_CzesciChanging(value);
					this.SendPropertyChanging();
					this._Typ_Czesci = value;
					this.SendPropertyChanged("Typ_Czesci");
					this.OnTyp_CzesciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_Czesci", DbType="NVarChar(100)")]
		public string Nazwa_Czesci
		{
			get
			{
				return this._Nazwa_Czesci;
			}
			set
			{
				if ((this._Nazwa_Czesci != value))
				{
					this.OnNazwa_CzesciChanging(value);
					this.SendPropertyChanging();
					this._Nazwa_Czesci = value;
					this.SendPropertyChanged("Nazwa_Czesci");
					this.OnNazwa_CzesciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numer_Katalogowy", DbType="NVarChar(100)")]
		public string Numer_Katalogowy
		{
			get
			{
				return this._Numer_Katalogowy;
			}
			set
			{
				if ((this._Numer_Katalogowy != value))
				{
					this.OnNumer_KatalogowyChanging(value);
					this.SendPropertyChanging();
					this._Numer_Katalogowy = value;
					this.SendPropertyChanged("Numer_Katalogowy");
					this.OnNumer_KatalogowyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stan_Magazyn", DbType="Int")]
		public System.Nullable<int> Stan_Magazyn
		{
			get
			{
				return this._Stan_Magazyn;
			}
			set
			{
				if ((this._Stan_Magazyn != value))
				{
					this.OnStan_MagazynChanging(value);
					this.SendPropertyChanging();
					this._Stan_Magazyn = value;
					this.SendPropertyChanged("Stan_Magazyn");
					this.OnStan_MagazynChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Czesci_Zakupy", Storage="_Zakupy", ThisKey="Id_Czesci", OtherKey="Id_Czesci")]
		public EntitySet<Zakupy> Zakupy
		{
			get
			{
				return this._Zakupy;
			}
			set
			{
				this._Zakupy.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Zakupy(Zakupy entity)
		{
			this.SendPropertyChanging();
			entity.Czesci = this;
		}
		
		private void detach_Zakupy(Zakupy entity)
		{
			this.SendPropertyChanging();
			entity.Czesci = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Zakupy")]
	public partial class Zakupy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Zakupu;
		
		private System.Nullable<int> _Id_Czesci;
		
		private System.Nullable<int> _Id_Klienta;
		
		private System.Nullable<int> _Ilosc;
		
		private System.Nullable<System.DateTime> _Data;
		
		private EntityRef<Czesci> _Czesci;
		
		private EntityRef<Klient> _Klient;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_ZakupuChanging(int value);
    partial void OnId_ZakupuChanged();
    partial void OnId_CzesciChanging(System.Nullable<int> value);
    partial void OnId_CzesciChanged();
    partial void OnId_KlientaChanging(System.Nullable<int> value);
    partial void OnId_KlientaChanged();
    partial void OnIloscChanging(System.Nullable<int> value);
    partial void OnIloscChanged();
    partial void OnDataChanging(System.Nullable<System.DateTime> value);
    partial void OnDataChanged();
    #endregion
		
		public Zakupy()
		{
			this._Czesci = default(EntityRef<Czesci>);
			this._Klient = default(EntityRef<Klient>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Zakupu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id_Zakupu
		{
			get
			{
				return this._Id_Zakupu;
			}
			set
			{
				if ((this._Id_Zakupu != value))
				{
					this.OnId_ZakupuChanging(value);
					this.SendPropertyChanging();
					this._Id_Zakupu = value;
					this.SendPropertyChanged("Id_Zakupu");
					this.OnId_ZakupuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Czesci", DbType="Int")]
		public System.Nullable<int> Id_Czesci
		{
			get
			{
				return this._Id_Czesci;
			}
			set
			{
				if ((this._Id_Czesci != value))
				{
					if (this._Czesci.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_CzesciChanging(value);
					this.SendPropertyChanging();
					this._Id_Czesci = value;
					this.SendPropertyChanged("Id_Czesci");
					this.OnId_CzesciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Klienta", DbType="Int")]
		public System.Nullable<int> Id_Klienta
		{
			get
			{
				return this._Id_Klienta;
			}
			set
			{
				if ((this._Id_Klienta != value))
				{
					if (this._Klient.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_KlientaChanging(value);
					this.SendPropertyChanging();
					this._Id_Klienta = value;
					this.SendPropertyChanged("Id_Klienta");
					this.OnId_KlientaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilosc", DbType="Int")]
		public System.Nullable<int> Ilosc
		{
			get
			{
				return this._Ilosc;
			}
			set
			{
				if ((this._Ilosc != value))
				{
					this.OnIloscChanging(value);
					this.SendPropertyChanging();
					this._Ilosc = value;
					this.SendPropertyChanged("Ilosc");
					this.OnIloscChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data", DbType="DateTime")]
		public System.Nullable<System.DateTime> Data
		{
			get
			{
				return this._Data;
			}
			set
			{
				if ((this._Data != value))
				{
					this.OnDataChanging(value);
					this.SendPropertyChanging();
					this._Data = value;
					this.SendPropertyChanged("Data");
					this.OnDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Czesci_Zakupy", Storage="_Czesci", ThisKey="Id_Czesci", OtherKey="Id_Czesci", IsForeignKey=true)]
		public Czesci Czesci
		{
			get
			{
				return this._Czesci.Entity;
			}
			set
			{
				Czesci previousValue = this._Czesci.Entity;
				if (((previousValue != value) 
							|| (this._Czesci.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Czesci.Entity = null;
						previousValue.Zakupy.Remove(this);
					}
					this._Czesci.Entity = value;
					if ((value != null))
					{
						value.Zakupy.Add(this);
						this._Id_Czesci = value.Id_Czesci;
					}
					else
					{
						this._Id_Czesci = default(Nullable<int>);
					}
					this.SendPropertyChanged("Czesci");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Klient_Zakupy", Storage="_Klient", ThisKey="Id_Klienta", OtherKey="Id_Klienta", IsForeignKey=true)]
		public Klient Klient
		{
			get
			{
				return this._Klient.Entity;
			}
			set
			{
				Klient previousValue = this._Klient.Entity;
				if (((previousValue != value) 
							|| (this._Klient.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Klient.Entity = null;
						previousValue.Zakupy.Remove(this);
					}
					this._Klient.Entity = value;
					if ((value != null))
					{
						value.Zakupy.Add(this);
						this._Id_Klienta = value.Id_Klienta;
					}
					else
					{
						this._Id_Klienta = default(Nullable<int>);
					}
					this.SendPropertyChanged("Klient");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Klient")]
	public partial class Klient : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Klienta;
		
		private string _Firma;
		
		private string _Imie;
		
		private string _Nazwisko;
		
		private string _Adres;
		
		private string _Kod_Pocztowy;
		
		private string _Miasto;
		
		private string _Email;
		
		private string _Telefon;
		
		private string _Notatki;
		
		private EntitySet<Zakupy> _Zakupy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_KlientaChanging(int value);
    partial void OnId_KlientaChanged();
    partial void OnFirmaChanging(string value);
    partial void OnFirmaChanged();
    partial void OnImieChanging(string value);
    partial void OnImieChanged();
    partial void OnNazwiskoChanging(string value);
    partial void OnNazwiskoChanged();
    partial void OnAdresChanging(string value);
    partial void OnAdresChanged();
    partial void OnKod_PocztowyChanging(string value);
    partial void OnKod_PocztowyChanged();
    partial void OnMiastoChanging(string value);
    partial void OnMiastoChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnTelefonChanging(string value);
    partial void OnTelefonChanged();
    partial void OnNotatkiChanging(string value);
    partial void OnNotatkiChanged();
    #endregion
		
		public Klient()
		{
			this._Zakupy = new EntitySet<Zakupy>(new Action<Zakupy>(this.attach_Zakupy), new Action<Zakupy>(this.detach_Zakupy));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Klienta", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id_Klienta
		{
			get
			{
				return this._Id_Klienta;
			}
			set
			{
				if ((this._Id_Klienta != value))
				{
					this.OnId_KlientaChanging(value);
					this.SendPropertyChanging();
					this._Id_Klienta = value;
					this.SendPropertyChanged("Id_Klienta");
					this.OnId_KlientaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firma", DbType="NVarChar(200)")]
		public string Firma
		{
			get
			{
				return this._Firma;
			}
			set
			{
				if ((this._Firma != value))
				{
					this.OnFirmaChanging(value);
					this.SendPropertyChanging();
					this._Firma = value;
					this.SendPropertyChanged("Firma");
					this.OnFirmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imie", DbType="NVarChar(100)")]
		public string Imie
		{
			get
			{
				return this._Imie;
			}
			set
			{
				if ((this._Imie != value))
				{
					this.OnImieChanging(value);
					this.SendPropertyChanging();
					this._Imie = value;
					this.SendPropertyChanged("Imie");
					this.OnImieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwisko", DbType="NVarChar(10)")]
		public string Nazwisko
		{
			get
			{
				return this._Nazwisko;
			}
			set
			{
				if ((this._Nazwisko != value))
				{
					this.OnNazwiskoChanging(value);
					this.SendPropertyChanging();
					this._Nazwisko = value;
					this.SendPropertyChanged("Nazwisko");
					this.OnNazwiskoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres", DbType="NVarChar(100)")]
		public string Adres
		{
			get
			{
				return this._Adres;
			}
			set
			{
				if ((this._Adres != value))
				{
					this.OnAdresChanging(value);
					this.SendPropertyChanging();
					this._Adres = value;
					this.SendPropertyChanged("Adres");
					this.OnAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kod_Pocztowy", DbType="NVarChar(100)")]
		public string Kod_Pocztowy
		{
			get
			{
				return this._Kod_Pocztowy;
			}
			set
			{
				if ((this._Kod_Pocztowy != value))
				{
					this.OnKod_PocztowyChanging(value);
					this.SendPropertyChanging();
					this._Kod_Pocztowy = value;
					this.SendPropertyChanged("Kod_Pocztowy");
					this.OnKod_PocztowyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Miasto", DbType="NVarChar(100)")]
		public string Miasto
		{
			get
			{
				return this._Miasto;
			}
			set
			{
				if ((this._Miasto != value))
				{
					this.OnMiastoChanging(value);
					this.SendPropertyChanging();
					this._Miasto = value;
					this.SendPropertyChanged("Miasto");
					this.OnMiastoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(200)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="VarChar(50)")]
		public string Telefon
		{
			get
			{
				return this._Telefon;
			}
			set
			{
				if ((this._Telefon != value))
				{
					this.OnTelefonChanging(value);
					this.SendPropertyChanging();
					this._Telefon = value;
					this.SendPropertyChanged("Telefon");
					this.OnTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notatki", DbType="NVarChar(1000)")]
		public string Notatki
		{
			get
			{
				return this._Notatki;
			}
			set
			{
				if ((this._Notatki != value))
				{
					this.OnNotatkiChanging(value);
					this.SendPropertyChanging();
					this._Notatki = value;
					this.SendPropertyChanged("Notatki");
					this.OnNotatkiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Klient_Zakupy", Storage="_Zakupy", ThisKey="Id_Klienta", OtherKey="Id_Klienta")]
		public EntitySet<Zakupy> Zakupy
		{
			get
			{
				return this._Zakupy;
			}
			set
			{
				this._Zakupy.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Zakupy(Zakupy entity)
		{
			this.SendPropertyChanging();
			entity.Klient = this;
		}
		
		private void detach_Zakupy(Zakupy entity)
		{
			this.SendPropertyChanging();
			entity.Klient = null;
		}
	}
}
#pragma warning restore 1591
